### ISSUE TITLE
Support for 0.9.3

### ISSUE THREAD

**Issue by trekze** [bibigone/k4a.net#13]
Only a couple weeks have passed and the body tracking has been updated again by Microsoft with a "v2 model" apparently. Kind of crazy, and I don't expect you to be able to update it again, but thought I'd let you know.

Will run the bodytracking without your C# layer today and report back if it's significantly improved :)

**Comment by bibigone** [comment]
The latest version supports Body Tracking 0.9.3:
* commit 333fd8f
* release [1.2.0](https://github.com/bibigone/k4a.net/releases/tag/v1.2.0)

**Comment by trekze** [comment]
oh nice. thank you!

side note: their body tracking is still not great
