### ISSUE TITLE
Components for Unity Project

### ISSUE THREAD

**Issue by LiuYishuo** [bibigone/k4a.net#16]
Hi!
First of all, great works! Helped me so much in building a unity project.
However, I think the readme for the unity part could improve a little. In total, there are 10 components needed:
* Part 1: from `..\K4AdotNet\bin\Debug\netstandard2.0`
    1. `K4AdotNet.deps.json`
    2. `K4AdotNet.dll`
    3. `K4AdotNet.pdb`
    4. `K4AdotNel.xml`
* Part 2: from `..\externals\k4a\windows-desktop\amd64`
    5. `depthengine_2_0.dll`
    6. `k4a.dll`
    7. `k4arecord.dll`
* Part 3: from `__custom_dir__\Azure Kinect Body Tracking SDK\tools`
    8. `k4abt.dll`
    9. `onnxruntime.dll`
    10. `dnn_model_2_0.onnx`

The 3rd part could be listed more clear in the readme. Copying the `k4abt.dll` only would not work. I locked down the two onnx components from reading the dependencies section of the main `Sdk.cs`.

**Comment by bibigone** [comment]
Hello @LiuYishuo,

Well spotted! We'll definitely improve this readme file.
