### ISSUE TITLE
Block(Box) Man Sample?

### ISSUE THREAD

**Issue by knat** [bibigone/k4a.net#19]
Thanks for the great work of the azure kinect .net wrapper.
There's a block man sample in kinect v2, which use joint orientation to rotate the block. Could you please provide the azure kinect block man sample in MonoGame or in Unity? I find the azure kinect joint orientation value is totally different than in v2.
![blockman](https://user-images.githubusercontent.com/10220052/67614799-89a74600-f7f5-11e9-8092-adb9801ea84f.png)
Kinect v2 block man sample: [KinectEvolution-XAML.zip](https://github.com/bibigone/k4a.net/files/3774486/KinectEvolution-XAML.zip)

**Comment by baSSiLL** [comment]
Hi @knat 
You can find some code working with joint orientations in Unity sample. Particularly, in [CharacterAnimator](https://github.com/bibigone/k4a.net/blob/master/K4AdotNet.Samples.Unity/Assets/Scripts/CharacterAnimator.cs) script.

**Comment by knat** [comment]
@baSSiLL Thanks, I have solved it.
