### ISSUE TITLE
Xbox Body Tracking SDK Capability?

### ISSUE THREAD

**Issue by prvallas** [bibigone/k4a.net#20]
I am wondering if the Xbox One S or X has the hardware capabilities to succesfully run the Body Tracking SDK.

**Comment by baSSiLL** [comment]
Hi @prvallas 
This page explicitly states Azure Kinect is not designed for use with XBOX
https://azure.microsoft.com/en-us/services/kinect-dk/#faq
I'm not sure that native binaries included in DK are ever compatible with XBOX platform. I have no experience developing for XBOX though.
