### ISSUE TITLE
Kinect One skeleton properties

### ISSUE THREAD

**Issue by Maxim-Zhukov** [bibigone/k4a.net#21]
Hello! Thanks a lot for your wrapper.

So, are there in Skeleton representer class such properties as in KinectOne Skeleton? 
For example, TrackingState for joints, FloorClipPlane, BodyLean etc.

**Comment by baSSiLL** [comment]
Hi @Maxim-Zhukov 
At the moment Azure Kinect Body Tracking SDK has more limited feature set compared to Kinect SDK 2. Basically, there are only joint positions and orientations. Recently released [0.9.4](https://docs.microsoft.com/en-us/azure/kinect-dk/body-sdk-download#v094) added confidence level for joints which is similar to tracking state of v2. K4A.net included this in [v1.3.0.](https://github.com/bibigone/k4a.net/releases/tag/v1.3.0)
