### ISSUE TITLE
How to achieve point cloud？

### ISSUE THREAD

**Issue by qazqaz12378** [bibigone/k4a.net#22]
How can I achieve the cloud?
After I follow the #15 code, the values ​​are all 0.
![image](https://user-images.githubusercontent.com/4353931/68380897-a9daeb80-018b-11ea-9514-51d7847f8f25.png)
![image](https://user-images.githubusercontent.com/4353931/68380907-b101f980-018b-11ea-8766-64c67f77b7b3.png)

**Comment by baSSiLL** [comment]
You only examine a single pixel from the top-left corner (x=0, y=0). Because of [specific shape of IR illumination](https://docs.microsoft.com/en-us/azure/kinect-dk/depth-camera#illumination-mask) pixels at the corners of depth frame are always invalid and have zero depth values. Hence corresponding points of the cloud are also invalid - all zeros.
Try to examine a pixel at the center (x=depthImage.Width/2, y=depthImage.Height/2).

**Comment by qazqaz12378** [comment]
This is my problem，I can already get the value correctly。
Please，How can I get the color value?

**Comment by baSSiLL** [comment]
To get color value for a single depth pixel use `Calibration.Convert2DTo2D(depthCoords, depthValue, CalibrationGeometry.Depth, CalibrationGeometry.Color)`. You'll get coords of a pixel in the color frame.
If you need colors for the whole depth frame use `Transformation.ColorImageToDepthCamera`.

**Comment by qazqaz12378** [comment]
I don't know how to use it.
I want to take out all the depths of the pixel colors and render the point cloud into a real color instead of a fixed color.
![image](https://user-images.githubusercontent.com/4353931/68462420-765d9700-0247-11ea-8fdc-fabe21219657.png)
![image](https://user-images.githubusercontent.com/4353931/68462430-7bbae180-0247-11ea-9ba1-1a10035c985e.png)

**Comment by baSSiLL** [comment]
The last argument for `ColorImageToDepthCamera` will be filled with colors for pixels of depth frame. Thus it should have image format `ColorBgra32` and resolution of depth frame. The first argument should be raw depth frame.
You can read more about image transformations in Azure Kinect Sensor SDK here.
https://docs.microsoft.com/en-us/azure/Kinect-dk/use-image-transformation

**Comment by qazqaz12378** [comment]
![image](https://user-images.githubusercontent.com/4353931/68464960-7f9d3280-024c-11ea-932e-0d3798805db3.png)
![image](https://user-images.githubusercontent.com/4353931/68464979-888e0400-024c-11ea-9b6f-be5a8fa576bf.png)
According to the above, I have made the above mistake after the modification, I am already at a loss.

**Comment by baSSiLL** [comment]
You allocated the array of improper size for transformed image. Bgra32 is 32-bit per pixel (1 byte per component), while in your array single pixel is short (16-bit) * 4 = 64 bits. Allocate either `int[]` array of size `depthWidth * depthHeight` or `byte[]` array of size `depthWidth * depthHeight * 4` depending on whether you need to work with individual color components or whole 32-bit color values. Also there is no need to explicitly specify a stride for Bgra32 format.

**Comment by qazqaz12378** [comment]
Thank you, the problem has been solved
