### ISSUE TITLE
Hardware compatibility

### ISSUE THREAD

**Issue by JMRMEDEV** [bibigone/k4a.net#32]
This is more a consult, instead of an issue itself.

I tried to use the official SDK for performing body tracking, but I got exceptions related with my graphic card. According to Microsoft's documentation, at least a nvidia gtx 1070 is required. My question is, does this sdk has the same restrictions? My PC has a nvidia gtx 860m.

**Comment by bibigone** [comment]
>  does this sdk has the same restrictions?

Yes, it does. Because it is built on the top of Microsoft's SDK. But in version 1.1 of Body Tracking SDK they added lite DNN model thus you GPU may be powerful enough to provide 30 FPS with this lite version.
