### ISSUE TITLE
Random Error while program is running

### ISSUE THREAD

**Issue by tctoki** [bibigone/k4a.net#33]
Hi, I am using the kinect azure to get the skeleton data, not accessing the depth.
Randomly there is an error saying 'Capture should contain the depth data.'
I am confused why this happened. It wasn't stopping the program. I just wonder why this happened.
Anyone can help? Thank you so much in advance!

`ArgumentException: Capture should contain the depth data.
Parameter name: capture
K4AdotNet.BodyTracking.Tracker.TryEnqueueCapture (K4AdotNet.Sensor.Capture capture, K4AdotNet.Timeout timeout) (at <5654af4d58fe436ba198b6384642a82b>:0)
K4AdotNet.Samples.Unity.SkeletonProvider.CaptureManager_CaptureReady (System.Object sender, K4AdotNet.Samples.Unity.CaptureEventArgs e) (at Assets/Scripts/k4a/SkeletonProvider.cs:85)
K4AdotNet.Samples.Unity.CaptureManager.Update () (at Assets/Scripts/k4a/CaptureManager.cs:56)`

**Comment by bibigone** [comment]
Please try the latest version (we've added checks to avoid this error).
