### ISSUE TITLE
capture function problem

### ISSUE THREAD

**Issue by fberna** [bibigone/k4a.net#36]
Hi guys,
I am using the capture function in order to create directly a .mkv file from Unity.
From the code below a get only a frame into the file. It looks like am continuously overwriting the file.
Have some of you any suggestions?

Thx
FB

```
private async Task KinectLoop()
    { 
    while (true)
        {
            using (K4AdotNet.Sensor.Capture capture = await Task.Run(() => kinect.GetCapture()).ConfigureAwait(true))
                {
                     using (var recorder = new Recorder(dstFilePath + "00.mkv", kinect, configuration))
                     {
                        if (capture != null)
                        {
                                recorder.WriteHeader();
                                recorder.WriteCapture(capture);
                       }
                    }
                }
        }
    }
```

**Comment by baSSiLL** [comment]
> It looks like am continuously overwriting the file.
Yes, that's exactly what's happening. Move createing/disposing of `recorder` and `recorder.WriteHeader` call out of the loop.
```c#
using (var recorder = new Recorder(dstFilePath + "00.mkv", kinect, configuration))
{
    recorder.WriteHeader();
    while (true)
    {
        // get capture
        recorder.WriteCapture(capture);
    }
}
```

**Comment by fberna** [comment]
> Move createing/disposing of recorder and recorder.WriteHeader call out of the loop.

I tried but like that Unity crashes every time. It is probably due to RAM overload.

**Comment by baSSiLL** [comment]
You should dispose `Capture` objects when finished working with them. In this case, right after calling `WriteCapture`.

**Comment by fberna** [comment]
> You should dispose Capture objects when finished working with them. In this case, right after calling WriteCapture.

In this way, I will have my file in the right format but with zero frames in it.

```
using (K4AdotNet.Sensor.Capture capture = await Task.Run(() => kinect.GetCapture()).ConfigureAwait(true)
           {
                using (var recorder = new Recorder(dstFilePath + "00.mkv", kinect, configuration))
                {
                    recorder.WriteHeader();
                    while (true)
                    {
                          recorder.WriteCapture(capture);
                          capture.Dispose();
                     }
                }
            }

```

**Comment by baSSiLL** [comment]
Apparently you should be getting `Capture` inside the loop before writing it to `recorder`.

**Comment by fberna** [comment]
It works! Thank you
