### ISSUE TITLE
Mismatch between images from DepthImageToPointCloud and ColorImageToDepthCamera

### ISSUE THREAD

**Issue by fberna** [bibigone/k4a.net#40]
Creating a mesh result in a mismacthing between vertices and colors. 
![image](https://user-images.githubusercontent.com/41567504/129334891-46d0cb5b-b182-4cad-b1e0-40d896fe9f7a.png)

Images are inserted with the correct resolution.
`transformation.DepthImageToPointCloud(capture.DepthImage, CalibrationGeometry.Depth, xyzImage);`
`transformation.ColorImageToDepthCamera(capture.DepthImage, capture.ColorImage, colorArrayImage);`

**Comment by bibigone** [comment]
Most likely, you're doing something wrong. You can find working code in WPF sample called K4AdotNet.Samples.Wpf.Viewer.
