### ISSUE TITLE
Some questions about Capture.ColorImage.SystemTimestamp

### ISSUE THREAD

**Issue by TristanWYL** [bibigone/k4a.net#41]
Hi bibigone, this is not a bug, but just check something with you.

1. Does **Capture.ColorImage.SystemTimestamp** definitely grow monotonically? Is it possible that one color image frame arrives at the host before other frames which generated earlier than it?
2. I used the system timestamp to replaced the device timestamp, and found that the system timestamp is not evenly distributed. Do you know what will affect the distribution of the system timestamp along the timeline?

In addition, may I ask one more question? When you work with the Kinect DK, have you ever came across with [this issue](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1676#issue-990961842)?

Thanks so much for your attention.

**Comment by bibigone** [comment]
1. According to my understanding, FIFO is used for frames transfer and receiving. Thus, SystemTimestamp should grow monotonically.
2. SystemTimestamp generated by local computer after frame receiving. But there is a log way between the frame capturing inside Kinect device and the receiving of the same frame in OS. This way includes some internal buffers, asynchronous logic, etc. This why DeviceTimestamp is much more reliable and useful in comparison with SystemTimestamp.
