### ISSUE TITLE
About TrackerConfiguration ProcessingMode

### ISSUE THREAD

**Issue by YJ-L-2017** [bibigone/k4a.net#43]
when ProcessingMode= TrackerProcessingMode.GpuCuda,the following prompt appears：
[W:onnxruntime:K4ABT_ORT_Environment, cuda_execution_provider.cc:1885 onnxruntime::CUDAExecutionProvider::GetCapability] CUDA kernel not found in registries for Op type: Sign node name: Sign
 [W:onnxruntime:K4ABT_ORT_Environment, fallback_cpu_capability.h:140 onnxruntime::GetCpuPreferedNodes] Force fallback to CPU execution for node: Shape__40
system:win10
cuda:11.1

**Comment by bibigone** [comment]
This output is not directly connected to this particular .NET wrapper around Azure Kinect Body Tracking SDK, because it is generated from internals of this native SDK.
