### ISSUE TITLE
Orbbec Femto Mega and Bolt wrapper

### ISSUE THREAD

**Issue by frenchtouchXR** [bibigone/k4a.net#47]
Dear Mister Bibigone, 

Are you planning to release an Orbbec Femto Mega/Bolt wrapper for dotNet ? 
Microsoft has discontinued the Azure Kinect... It seems Orbbec is continuing this amazing technology. 

Best

**Comment by bibigone** [comment]
See commit 6ef134187ee7ff39524f87d9510a6e174206a12f

**Comment by bibigone** [comment]
Added full support for OrbbecSDK K4A Wrapper.
