### ISSUE TITLE
Error when trying to create image from array with custom image format

### ISSUE THREAD

**Issue by carlmill** [bibigone/k4a.net#48]
I'm trying to access the point cloud data using the Orbbec version of the library. When I try to create a new image using ImageFormat.Custom, I get the following error message

"Cannot create image with format Custom, size 640x576 pixels, stride 3840 bytes from buffer of size 2211840 bytes."

short[] xyzImageBuffer = new short[depth.WidthPixels * depth.HeightPixels * 3];
int xyzImageStride = depth.WidthPixels * sizeof(short) * 3;
using (var transofrimation = calibration.CreateTransformation())
{
    using (var xyzImage = Image.CreateFromArray(xyzImageBuffer, ImageFormat.Custom, 
                                                                            depth.WidthPixels,depth.HeightPixels,xyzImageStride))
    {
      transofrimation.DepthImageToPointCloud(depth, CalibrationGeometry.Depth, xyzImage);
    }
}

**Comment by bibigone** [comment]
Hello,

This is limitation of **OrbbecSDK K4A Wrapper**. When using it, it is better to avoid images creation from arrays:

```csharp
   short[] xyzImageBuffer = new short[depth.WidthPixels * depth.HeightPixels * 3];
   using (var transformation = new Transformation(in calibration))
   {
          using (var xyzImage = new Image(ImageFormat.Custom, depth.WidthPixels, depth.HeightPixels, depth.WidthPixels * 6))
          {
                transformation.DepthImageToPointCloud(depthImage, CalibrationGeometry.Depth, xyzImage);
                Marshal.Copy(xyzImage.Buffer, xyzImageBuffer, 0, xyzImageBuffer.Length);
          }
   }
```
