### ISSUE TITLE
Mirro

### ISSUE THREAD

**Issue by yocop** [bibigone/k4a.net#5]
How Can I get Mirror body tracker image？thanks

**Comment by baSSiLL** [comment]
Hi @Itpyc
The exact way to mirror depends on your task.
If it's only for render purposes then the easiest way is to apply a transform to UI elements. For instance, in **BodyTracker** sample you can set appropriate **LayoutTransform** for **CapturedImage** style.
```
        <Style x:Key="CapturedImage" TargetType="Image">
            <Setter Property="Margin" Value="1"/>
            <Setter Property="LayoutTransform">
                <Setter.Value>
                    <ScaleTransform ScaleX="-1" ScaleY="1"/>
                </Setter.Value>
            </Setter>
        </Style>
```
If you need to process skeletons in mirrored coordinate space then you can invert X coordinate of joint positions obtained from the API.
